version: '3'
services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - SalesPeek_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: SalesPeek_db
  
  pgadmin:
    container_name: SalesPeek_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - SalesPeek_pgadmin_data:/var/lib/pgadmin
    links:
      - "postgres:pg-link"
    

  strapi:
    image: strapi/strapi
    container_name: SalesPeek_strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/frontend/src

    ports:
      - "3000:3000"
    container_name: SalesPeek_frontend
    command: npm start
    depends_on:
      - strapi
    links:
      - "strapi: backend-server"
    environment:
      - REACT_APP_API=127.0.0.1:1337

volumes:
  SalesPeek_data:
  SalesPeek_pgadmin_data: